"""Initial schema

Revision ID: ac3292aad149
Revises: 
Create Date: 2025-11-29 19:55:29.095760

"""
from alembic import op
import sqlalchemy as sa


revision = 'ac3292aad149'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_category', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_org', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('idx_audit_type_time', 'audit_logs', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('federated_rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('min_devices', sa.Integer(), nullable=True),
    sa.Column('aggregation_method', sa.Enum('FEDAVG', 'KRUM', 'TRIMMED_MEAN', name='aggregationmethodenum'), nullable=False),
    sa.Column('differential_privacy', sa.Boolean(), nullable=True),
    sa.Column('privacy_budget', sa.Float(), nullable=True),
    sa.Column('byzantine_tolerance', sa.Integer(), nullable=True),
    sa.Column('devices_participated', sa.Integer(), nullable=True),
    sa.Column('updates_received', sa.Integer(), nullable=True),
    sa.Column('updates_accepted', sa.Integer(), nullable=True),
    sa.Column('updates_rejected', sa.Integer(), nullable=True),
    sa.Column('previous_model_version', sa.Integer(), nullable=True),
    sa.Column('new_model_version', sa.Integer(), nullable=True),
    sa.Column('accuracy_improvement', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_round_number', 'federated_rounds', ['round_number'], unique=False)
    op.create_index('idx_round_status', 'federated_rounds', ['status'], unique=False)
    op.create_index(op.f('ix_federated_rounds_round_number'), 'federated_rounds', ['round_number'], unique=True)
    op.create_table('global_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights_blob', sa.Text(), nullable=True),
    sa.Column('model_architecture', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('devices_contributed', sa.Integer(), nullable=True),
    sa.Column('total_samples', sa.Integer(), nullable=True),
    sa.Column('aggregation_method', sa.Enum('FEDAVG', 'KRUM', 'TRIMMED_MEAN', name='aggregationmethodenum'), nullable=True),
    sa.Column('differential_privacy_enabled', sa.Boolean(), nullable=True),
    sa.Column('privacy_budget', sa.Float(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('training_duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_version', 'global_models', ['version'], unique=False)
    op.create_index(op.f('ix_global_models_version'), 'global_models', ['version'], unique=True)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_org_api_key', 'organizations', ['api_key'], unique=False)
    op.create_index(op.f('ix_organizations_api_key'), 'organizations', ['api_key'], unique=True)
    op.create_table('threat_intelligence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern_name', sa.String(length=255), nullable=False),
    sa.Column('pattern_signature', sa.Text(), nullable=True),
    sa.Column('threat_category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='threatseverityenum'), nullable=False),
    sa.Column('prevalence', sa.Integer(), nullable=True),
    sa.Column('detection_rules', sa.JSON(), nullable=True),
    sa.Column('indicators_of_compromise', sa.JSON(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('mitigation_effectiveness', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threat_intel_category', 'threat_intelligence', ['threat_category'], unique=False)
    op.create_index('idx_threat_intel_severity', 'threat_intelligence', ['severity'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.Enum('CAMERA', 'SENSOR', 'THERMOSTAT', 'LOCK', 'MEDICAL', 'INDUSTRIAL', 'OTHER', name='devicetypeenum'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'COMPROMISED', 'MAINTENANCE', name='devicestatusenum'), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('baseline_cpu', sa.Float(), nullable=True),
    sa.Column('baseline_network', sa.Float(), nullable=True),
    sa.Column('baseline_requests', sa.Float(), nullable=True),
    sa.Column('baseline_memory', sa.Float(), nullable=True),
    sa.Column('current_model_version', sa.Integer(), nullable=True),
    sa.Column('local_model_accuracy', sa.Float(), nullable=True),
    sa.Column('total_contributions', sa.Integer(), nullable=True),
    sa.Column('last_contribution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('hardware_info', sa.JSON(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_last_seen', 'devices', ['last_seen'], unique=False)
    op.create_index('idx_device_org', 'devices', ['organization_id'], unique=False)
    op.create_index('idx_device_status', 'devices', ['status'], unique=False)
    op.create_table('device_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('cpu_usage', sa.Float(), nullable=False),
    sa.Column('memory_usage', sa.Float(), nullable=True),
    sa.Column('network_traffic', sa.Float(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('connection_attempts', sa.Integer(), nullable=True),
    sa.Column('disk_usage', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('custom_metrics', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_device_time', 'device_metrics', ['device_id', 'timestamp'], unique=False)
    op.create_index('idx_metrics_timestamp', 'device_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_device_metrics_timestamp'), 'device_metrics', ['timestamp'], unique=False)
    op.create_table('model_updates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('global_model_version', sa.Integer(), nullable=False),
    sa.Column('weights_blob', sa.Text(), nullable=True),
    sa.Column('update_hash', sa.String(length=64), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('local_accuracy', sa.Float(), nullable=True),
    sa.Column('local_loss', sa.Float(), nullable=True),
    sa.Column('epochs_trained', sa.Integer(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('is_byzantine', sa.Boolean(), nullable=True),
    sa.Column('validation_score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('aggregated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['global_model_version'], ['global_models.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_update_device_version', 'model_updates', ['device_id', 'global_model_version'], unique=False)
    op.create_index('idx_update_submitted', 'model_updates', ['submitted_at'], unique=False)
    op.create_table('threats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='threatseverityenum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.Integer(), nullable=True),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threat_device', 'threats', ['device_id'], unique=False)
    op.create_index('idx_threat_severity_time', 'threats', ['severity', 'detected_at'], unique=False)
    op.create_index('idx_threat_unresolved', 'threats', ['is_resolved', 'severity'], unique=False)
    op.create_index(op.f('ix_threats_detected_at'), 'threats', ['detected_at'], unique=False)
    op.create_index(op.f('ix_threats_severity'), 'threats', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threats_severity'), table_name='threats')
    op.drop_index(op.f('ix_threats_detected_at'), table_name='threats')
    op.drop_index('idx_threat_unresolved', table_name='threats')
    op.drop_index('idx_threat_severity_time', table_name='threats')
    op.drop_index('idx_threat_device', table_name='threats')
    op.drop_table('threats')
    op.drop_index('idx_update_submitted', table_name='model_updates')
    op.drop_index('idx_update_device_version', table_name='model_updates')
    op.drop_table('model_updates')
    op.drop_index(op.f('ix_device_metrics_timestamp'), table_name='device_metrics')
    op.drop_index('idx_metrics_timestamp', table_name='device_metrics')
    op.drop_index('idx_metrics_device_time', table_name='device_metrics')
    op.drop_table('device_metrics')
    op.drop_index('idx_device_status', table_name='devices')
    op.drop_index('idx_device_org', table_name='devices')
    op.drop_index('idx_device_last_seen', table_name='devices')
    op.drop_table('devices')
    op.drop_index('idx_threat_intel_severity', table_name='threat_intelligence')
    op.drop_index('idx_threat_intel_category', table_name='threat_intelligence')
    op.drop_table('threat_intelligence')
    op.drop_index(op.f('ix_organizations_api_key'), table_name='organizations')
    op.drop_index('idx_org_api_key', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_global_models_version'), table_name='global_models')
    op.drop_index('idx_model_version', table_name='global_models')
    op.drop_table('global_models')
    op.drop_index(op.f('ix_federated_rounds_round_number'), table_name='federated_rounds')
    op.drop_index('idx_round_status', table_name='federated_rounds')
    op.drop_index('idx_round_number', table_name='federated_rounds')
    op.drop_table('federated_rounds')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index('idx_audit_type_time', table_name='audit_logs')
    op.drop_index('idx_audit_org', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###